# Generated by Django 5.2 on 2025-04-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
