# Generated by Django 5.2 on 2025-04-11 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='reclutador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
